---
AWSTemplateFormatVersion: '2010-09-09'
Description: deploying a lamp stack using bitnami ami which has reconfigured lamp stack

Resources:
  myinstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01816d07b1128cd2d
      KeyName: web-dev
      SecurityGroupIds:
        - !Ref mysecurityGroup
      Tags:
        - Key: Name
          Value: 'web01'

  mysecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow SSH and HTTP traffic"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

Outputs:
  InstancePublicIp:
    Value: !GetAtt myinstance.PublicIp

        
